spring:
  application:
    name: main
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    # https://www.h2database.com/html/features.html#in_memory_databases 참조
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

server:
  port: 5000

app:
  client:
    base-url: "http://localhost:5000"
    url:
      school: "http://localhost:5000"
